### ISSUE TITLE
Getting an error  while compiling html.js

### ISSUE THREAD

**Issue by Maciej001** [njosefbeck/gatsby-plugin-stripe-checkout#1]
After adding both: gatsby-plugin-stripe-checkout and gatsby-plugin-strip-elements I am getting a similar error:
![screen shot 2017-12-14 at 10 01 18](https://user-images.githubusercontent.com/1102047/33986696-4661f0b4-e0b6-11e7-96cb-8bb636a73037.png)

**Comment by njosefbeck** [comment]
Hello! Thanks for bringing this to my attention. I've fixed this, and have published the fix to NPM. If you wouldn't mind testing again, and verifying that Gatsby now successfully builds, that'd be much appreciated. Thanks!

**Comment by njosefbeck** [comment]
Closing as this should be fixed now.
