### ISSUE TITLE
Please improve the Readme

### ISSUE THREAD

**Issue by DavidSabine** [njosefbeck/gatsby-plugin-stripe-checkout#5]
Hi,

(BTW: I really like the work you've done and the plugins are very helpful.  I submit these issues merely as a 'nice to have' for newbs.)

Given there are a few Stripe plugins, it is difficult (for someone not yet familiar with Stripe's APIs) to know how the plugins overlap.

https://www.gatsbyjs.org/packages/gatsby-plugin-stripe/?=stripe

It would be very helpful if the Readme for each of those plugins would include a sentence like:
>Use this plugin when you need... and do not need...
or
>This plugin is different than `Gatsby-plugin-stripe-______` because...
or
>This plugin extends the functionality of `Gatsby-plugin-stripe-______`

**Comment by njosefbeck** [comment]
Hello again!

I appreciate your kind words, and thanks for helping me improve these projects. I've now updated all the READMEs for the three gatsby plugins that I maintain. If you could go and re-read their READMEs, and let me know if they're clearer, that'd be helpful. Also let me know if you feel like they could be clarified even further. I'm open to suggestions!

* gatsby-plugin-stripe-checkout (current repo)
* [gatsby-plugin-stripe](https://github.com/njosefbeck/gatsby-plugin-stripe)
* [gatsby-source-stripe](https://github.com/njosefbeck/gatsby-source-stripe)

Thanks again for your help.

**Comment by DavidSabine** [comment]
Huge thanks.  Waaaaaaay clearer now.

**Comment by njosefbeck** [comment]
I'm glad! I'll close this issue now. Feel free to open again if ever more clarifications are needed. Thanks again.
